
INSERT INTO district_config (id, name) VALUES (1, 'Ariyalur');
INSERT INTO district_config (id, name) VALUES (2, 'Chengalpattu');
INSERT INTO district_config (id, name) VALUES (3, 'Chennai');
INSERT INTO district_config (id, name) VALUES (4, 'Coimbatore');
INSERT INTO district_config (id, name) VALUES (5, 'Cuddalore');
INSERT INTO district_config (id, name) VALUES (6, 'Dharmapuri');
INSERT INTO district_config (id, name) VALUES (7, 'Dindigul');
INSERT INTO district_config (id, name) VALUES (8, 'Erode');
INSERT INTO district_config (id, name) VALUES (9, 'Kallakurichi');
INSERT INTO district_config (id, name) VALUES (10, 'Kancheepuram');
INSERT INTO district_config (id, name) VALUES (11, 'Karur');
INSERT INTO district_config (id, name) VALUES (12, 'Krishnagiri');
INSERT INTO district_config (id, name) VALUES (13, 'Madurai');
INSERT INTO district_config (id, name) VALUES (14, 'Mayiladuthurai');
INSERT INTO district_config (id, name) VALUES (15, 'Nagapattinam');
INSERT INTO district_config (id, name) VALUES (16, 'Kanniyakumari');
INSERT INTO district_config (id, name) VALUES (17, 'Namakkal');
INSERT INTO district_config (id, name) VALUES (18, 'Perambalur');
INSERT INTO district_config (id, name) VALUES (19, 'Pudukottai');
INSERT INTO district_config (id, name) VALUES (20, 'Ramanathapuram');
INSERT INTO district_config (id, name) VALUES (21, 'Ranipet');
INSERT INTO district_config (id, name) VALUES (22, 'Salem');
INSERT INTO district_config (id, name) VALUES (23, 'Sivagangai');
INSERT INTO district_config (id, name) VALUES (24, 'Tenkasi');
INSERT INTO district_config (id, name) VALUES (25, 'Thanjavur');
INSERT INTO district_config (id, name) VALUES (26, 'Theni');
INSERT INTO district_config (id, name) VALUES (27, 'Thiruvallur');
INSERT INTO district_config (id, name) VALUES (28, 'Thiruvarur');
INSERT INTO district_config (id, name) VALUES (29, 'Thoothukudi');
INSERT INTO district_config (id, name) VALUES (30, 'Trichirappalli');
INSERT INTO district_config (id, name) VALUES (31, 'Thirunelveli');
INSERT INTO district_config (id, name) VALUES (32, 'Tirupathur');
INSERT INTO district_config (id, name) VALUES (33, 'Tiruppur');
INSERT INTO district_config (id, name) VALUES (34, 'Tiruvannamalai');
INSERT INTO district_config (id, name) VALUES (35, 'The Nilgiris');
INSERT INTO district_config (id, name) VALUES (36, 'Vellore');
INSERT INTO district_config (id, name) VALUES (37, 'Viluppuram');
INSERT INTO district_config (id, name) VALUES (38, 'Virudhunagar');


INSERT INTO area_config (id, area, districtId, pincodes) VALUES (1, 'Pudukurichy', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (2, 'Peravoorani', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (3, 'Sethubavachatram', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (4, 'Soolakarai', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (5, 'Valayapatti', 13, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (6, 'R.Reddiapatti', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (7, 'Seithur', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (8, 'Koratty', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (9, 'Kunichi', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (10, 'Alangayam', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (11, 'Mittur', 12, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (12, 'Kavalur', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (13, 'Singarapet', 34, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (14, 'Matrapalli', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (15, 'Eggore', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (16, 'Natramapalli', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (17, 'Natrampalli', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (18, 'Pitchur', 34, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (19, 'Jolarpet', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (20, 'Pudukkottai', 19, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (21, 'Elanthaikkulam', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (22, 'Olaiyur', 19, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (23, 'Gummidipoondi', 27, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (24, 'Durainallur', 27, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (25, 'Perambalur', 18, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (26, 'Pattukottai', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (27, 'Tondiarpet', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (28, 'Karur', 11, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (29, 'Periyar Nagar', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (30, 'Appanaickenpatti', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (31, 'South Avinashipalayam', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (32, 'Angalakurichi', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (33, 'Koothur', 31, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (34, 'Keelapalur', 1, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (35, 'Gudalur', 26, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (36, 'Venmani', 15, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (37, 'Nenmeni', 26, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (38, 'Madurai', 13, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (39, 'Salem', 22, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (40, 'VADASERI', 16, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (41, 'Watrap', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (42, 'A.Thulukkapatti', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (43, 'S.Kodikulam', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (44, 'Punnai', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (45, 'Katpadi', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (46, 'Alamarathur', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (47, 'Andimadam', 1, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (48, 'Pappakudy', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (49, 'Ayyur', 7, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (50, 'Periyakarukai', 5, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (51, 'Valapady', 22, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (52, 'Kolathur', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (53, 'Vyasarpadi', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (54, 'Pongalur', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (55, 'Panapalayam', 17, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (56, 'Manali', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (57, 'Salai', 15, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (58, 'Erode', 8, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (59, 'Kanji', 34, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (60, 'Rajanthangal', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (61, 'Vellore', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (62, 'Athipattu', 27, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (63, 'Madukkur', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (64, 'Thamarankottai', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (65, 'Mariyammankovil', 15, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (66, 'Thiruppurambiyam', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (67, 'Thiruppanadhal', 5, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (68, 'Aviyoor', 20, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (69, 'Kariapatty', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (70, 'Pulvaikarai', 8, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (71, 'Srivilliputhur', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (72, 'Perundurai', 8, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (73, 'JAYANKONDAM', 1, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (74, 'Pollachi', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (75, 'T.PALUR', 1, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (76, 'Thaluthalaimedu', 28, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (77, 'THIRUKANURPATTI', 19, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (78, 'Thiruvellavoyal', 27, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (79, 'Thanjavur', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (80, 'Aduthurai', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (81, 'Papanasam', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (82, 'Karambayam', 28, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (83, 'Kundadam', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (84, 'Uthiyur', 8, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (85, 'Rasathavalasu', 8, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (86, 'Thiruthangal', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (87, 'Sukkiravarpatti', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (88, 'Sakkottai', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (89, 'Kumbakonam', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (90, 'Rayakottai', 12, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (91, 'Bargur', 12, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (92, 'Shoolagiri', 12, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (93, 'Anaicut', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (94, 'Pallikonda', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (95, 'Sathumadurai', 13, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (96, 'Kilpallipet', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (97, 'Karnambut', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (98, 'Arcot', 21, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (99, 'Itchipudur', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (100, 'SIRUVACHUR', 18, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (101, 'ESANAI', 37, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (102, 'KRISHNAPURAM', 5, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (103, 'Gomangalampudur', 22, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (104, 'Adirampattinam', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (105, 'Palayakottai', 31, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (106, 'Santhavasal', 19, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (107, 'THENOOR', 13, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (108, 'KEELAPERAMBALUR', 18, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (109, 'Iyerpady', 31, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (110, 'Olapalayam', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (111, 'Elavoor', 16, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (112, 'Kumbakonam', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (113, 'Rajanthottam', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (114, 'Thirunageswaram', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (115, 'POONDI', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (116, 'Saliyamangalam', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (117, 'Ayyampettai', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (118, 'Melattur', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (119, 'G.N.Patti', 7, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (120, 'Thulukkapatti', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (121, 'Aruppukottai', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (122, 'Periyapuliyampatti', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (123, 'Palayampatti', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (124, 'Velayuthapuram', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (125, 'Pandalgudi', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (126, 'Tamilpadi', 6, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (127, 'Vembakottai', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (128, 'Sevalpatti', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (129, 'Gangarakottai', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (130, 'Sattur', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (131, 'N.Subbiahpuram', 29, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (132, 'Sivakasi', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (133, 'Malliputhur', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (134, 'Alangulam', 24, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (135, 'Mudangiar', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (136, 'Adhamanagalam', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (137, 'KAIKALATHUR', 10, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (138, 'PERALI', 17, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (139, 'Paraipatti', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (140, 'Min nagar', 15, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (141, 'Vallam', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (142, 'Eachankottai', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (143, 'Thuraiyur', 30, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (144, 'Mullukudi', 28, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (145, 'Kurichy', 16, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (146, 'Okkanadu keelaiyur', 28, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (147, 'Muthuramalingapuram', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (148, 'Thorapadi', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (149, 'Orathanadu', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (150, 'Thakkolam', 21, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (151, 'Thogarapalli', 12, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (152, 'Denkanikottai', 12, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (153, 'Kamandoddy', 6, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (154, 'Attur', 22, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (155, 'Paravakkal', 31, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (156, 'Moarasapalli', 6, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (157, 'Upparapally', 6, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (158, 'Ambur', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (159, 'Somalapuram', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (160, 'Bhavani Barrage', 8, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (161, 'Marudhur', 15, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (162, 'Uranipuram', 13, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (163, 'P.N.Palayam', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (164, 'Madhampatty', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (165, 'Mallankinaru', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (166, 'Virudhunagar', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (167, 'Veeramarasampettai', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (168, 'Budalur', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (169, 'Perambur', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (170, 'EACHANGADU', 15, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (171, 'Mambakkam', 3, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (172, 'Indranagar', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (173, 'Vadugapatty', 22, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (174, 'Thudiyalur', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (175, 'A.METTUR', 22, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (176, 'Poolankinar', 29, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (177, 'Agaram', 18, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (178, 'Somayampalayam', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (179, 'Nariganapuram', 6, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (180, 'Ariyalam', 18, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (181, 'Samuthiram', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (182, 'Vinnavanur', 37, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (183, 'Vettavalam', 34, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (184, 'Samathur', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (185, 'KKD Nagar', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (186, 'Koilpalayam', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (187, 'SATHAMANGALAM', 13, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (188, 'MANGOON', 18, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (189, 'Anaimalai', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (190, 'NADUVALUR', 5, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (191, 'AMBAPUR', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (192, 'Ellapalayam', 17, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (193, 'Gurubarapally', 12, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (194, 'Padikasuvaithanpatty', 7, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (195, 'MGC Palayam', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (196, 'Thottiyapatti', 13, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (197, 'Mamsapuram', 38, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (198, 'Vinnamangalam', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (199, 'Udeyendiram', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (200, 'Pernambut', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (201, 'Mudichur', 3, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (202, 'Kolathupalayam', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (203, 'Mulanur', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (204, 'Mazhaiyur', 22, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (205, 'Thiruvanmaiyur', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (206, 'Kilavankattur', 15, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (207, 'Royapuram', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (208, 'Bagalur', 12, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (209, 'Saravanampatty', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (210, 'Polur', 34, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (211, 'Selaiyur', 3, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (212, 'Madambakkam', 3, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (213, 'NANNAI', 28, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (214, 'Ennore', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (215, 'Coimbatore', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (216, 'Mangalamedu', 5, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (217, 'KALANIVASAL', 23, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (218, 'Devanurpudur', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (219, 'Mosur', 12, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (220, 'Thandrampet', 34, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (221, 'Vembakkam', 34, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (222, 'Sastri Nagar', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (223, 'Adyar', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (224, 'Melpadi', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (225, 'Thuckalay', 16, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (226, 'Melvenkatapuram', 36, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (227, 'Sholingur', 21, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (228, 'Unamanchery', 27, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (229, 'Mugundarayapuram', 34, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (230, 'Nilakottai', 7, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (231, 'Nagercoil', 16, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (232, 'Thadikarankonam', 16, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (233, 'Vallankumaravilai', 16, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (234, 'Vadasery', 16, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (235, 'Kathirnaickenpalayam', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (236, 'Palappampatty', 17, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (237, 'Asaripallam', 16, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (238, 'Udumalpet', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (239, 'Besant Nagar', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (240, 'Tharamani', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (241, 'Elamangalam', 33, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (242, 'K.Vilakku', 15, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (243, 'Pallavaram East', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (244, 'Pattabiram', 27, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (245, 'Sekkadu', 27, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (246, 'Kamaraj Nagar', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (247, 'Velachery', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (248, 'Sembium', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (249, 'IIT', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (250, 'Poothamedur', 31, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (251, 'Kodavasal', 28, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (252, 'Kankeyanagaram', 28, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (253, 'Thiruvidachery', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (254, 'Manalagaram', 28, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (255, 'Edakeezhaiyur', 15, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (256, 'Sonapettai', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (257, 'Melavasal', 19, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (258, 'Vaduvur', 28, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (259, 'Sathanur', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (260, 'Moovarkottai', 15, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (261, 'Pullavarayankudikadu', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (262, 'Rishiyur', 6, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (263, 'Chettichatram', 7, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (264, 'Ammapettai', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (265, 'Harithwaramangalam', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (266, 'POLLACHI', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (267, 'TRICHY', 30, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (268, 'Thayanur', 30, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (269, 'Vanur', 37, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (270, 'Gandamanur', 26, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (271, 'Pallikaranai', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (272, 'Medavakkam', 3, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (273, 'Pudukrichy', 25, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (274, 'Chennai karapakkam', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (275, 'Marakkanam', 37, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (276, 'Murukkery', 15, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (277, 'Panaiyur', 4, '');
INSERT INTO area_config (id, area, districtId, pincodes) VALUES (278, 'Sempatty', 13, '');
